language: node_js
node_js:
- '0.10'
env:
  global:
    - secure: T/TQF2JDzdaw5jmPsDnM+CXZJIncPSOj3qPevrzURP/g2+gEj0ogHjr86IKhDGNyNNyJIdKQCiy5pKFFqy8UkA6HFQ71SgRqtR+Kn/4httW5ZcouBRJMNuGXdJ8ORu+C2PLv/IwqVnGK8ECYv+0nrl9LIXXA6Skzkqj68U24FbY=
    - secure: dhei8bL0TYLt3bbOUJh371vpecrOwlrIlHEVcck8HyjIWK8g+ADvfjYy73YH2ZXJnzQNXpn6qitUtB3UK1hypvMeBKV7RTb1ZPUqMrrpgN5nsgumeb5RHClZc7U7YJSRNB/aZmJqAtTPthgsbFaNEIfYCigA/F64OlQfWN73Pwc=
